Feature: User can add a recipe
  In order to expand available recipes
  As a user
  I want to add a new recipe

  Scenario: Happy Home Path
    Given the user "clyde@brewit.org" with password "mypw"
    When I go to the homepage
    And I click "Log In"
    And I fill in "clyde@brewit.org" for "Email"
    And I fill in "mypw" for "Password"
    And I press "Sign in"
    And I press "Build"
    And I fill in "Brown Saison" for "Name"
    And I fill in "Pretty tasty!" for "Description"
    And I fill in "6g" for "Batch size"
    And I fill in "75" for "Mash"
    And I fill in "149" for "Mash temp"
    And I fill in "90" for "Boil length"
    And I choose "Hops" for "Type"
    And I choose "Saaz" for "Ingredient name"
    And I choose "1" for "Quantity"
    And I choose "Boil" for "Usage"
    And I fill in "60" for "Duration"
    And I choose "mins" for "Unit"
    And I press "Save Recipe"
    And I go to the homepage
    And I click "Recipes"
    Then I should see "Brown Saison"
    And I should see "Pretty tasty!"


  Scenario: Happy Build Path
    Given the user "clyde@brewit.org" with password "mypw"
    When I go to the homepage
    And I click "Log In"
    And I fill in "clyde@brewit.org" for "Email"
    And I fill in "mypw" for "Password"
    And I press "Sign in"
    And I click "Recipes"
    And I fill in "Brown Saison" for "Name"
    And I fill in "Pretty tasty!" for "Description"
    And I fill in "6g" for "Batch size"
    And I fill in "75" for "Mash"
    And I fill in "149" for "Mash temp"
    And I fill in "90" for "Boil length"
    And I choose "Hops" for "Type"
    And I choose "Saaz" for "Ingredient name"
    And I choose "1" for "Quantity"
    And I choose "Boil" for "Usage"
    And I fill in "60" for "Duration"
    And I choose "mins" for "Unit"
    And I press "Save Recipe"
    Then I should see "Brown Saison"
    And I should see "Pretty tasty!"

  Scenario: Duplicate Name
    Given the user "clyde@brewit.org" with password "mypw"
    When I go to the homepage
    And I click "Log In"
    And I fill in "clyde@brewit.org" for "Email"
    And I fill in "mypw" for "Password"
    And I press "Sign in"
    And I press "Build"
    And I fill in "Classic" for "Name"
    And I fill in "Pretty tasty!" for "Description"
    And I fill in "6g" for "Batch size"
    And I fill in "75" for "Mash"
    And I fill in "149" for "Mash temp"
    And I fill in "90" for "Boil length"
    And I choose "Hops" for "Type"
    And I choose "Saaz" for "Ingredient name"
    And I choose "1" for "Quantity"
    And I choose "Boil" for "Usage"
    And I fill in "60" for "Duration"
    And I choose "mins" for "Unit"
    And I press "Save Recipe"
    Then I should see "Classic is already assigned"

  Scenario: Duplicate Name
    Given the user "clyde@brewit.org" with password "mypw"
    When I go to the homepage
    And I click "Log In"
    And I fill in "clyde@brewit.org" for "Email"
    And I fill in "mypw" for "Password"
    And I press "Sign in"
    And I press "Build"
    And I fill in "Pretty tasty!" for "Description"
    And I fill in "6g" for "Batch size"
    And I fill in "75" for "Mash"
    And I fill in "149" for "Mash temp"
    And I fill in "90" for "Boil length"
    And I choose "Hops" for "Type"
    And I choose "Saaz" for "Ingredient name"
    And I choose "1" for "Quantity"
    And I choose "Boil" for "Usage"
    And I fill in "60" for "Duration"
    And I choose "mins" for "Unit"
    And I press "Save Recipe"
    Then I should see "A name is required to create a new recipe"